# Handover-RL V2.0 Docker Compose Configuration
# Usage: docker-compose up -d

version: '3.8'

services:
  # ============================================================================
  # Main Application - Training & Development
  # ============================================================================
  handover-rl:
    build:
      context: .
      dockerfile: Dockerfile
    image: handover-rl:v2.0
    container_name: handover-rl-main
    hostname: handover-rl

    # Resource limits (adjust based on your hardware)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

    # GPU support (uncomment if using GPU)
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    # Volumes for persistent data
    volumes:
      # Source code (for development)
      - ./src:/app/src:ro
      - ./config:/app/config:ro
      - ./tests:/app/tests:ro

      # Data directories (read-write)
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs

      # Orbit-engine integration (parallel directory)
      - ../orbit-engine:/app/orbit-engine:ro

      # Optional: Mount TLE data
      # - ../orbit-engine/data/tle_data:/app/orbit-engine/data/tle_data:ro

    # Environment variables
    environment:
      - PYTHONPATH=/app:/app/src:/app/orbit-engine
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - OMP_NUM_THREADS=4
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - WANDB_MODE=${WANDB_MODE:-offline}

    # Ports
    ports:
      - "6006:6006"  # TensorBoard
      - "8888:8888"  # Jupyter (if enabled)

    # Working directory
    working_dir: /app

    # Command: Interactive shell (override for specific tasks)
    command: /bin/bash

    # Keep container running
    tty: true
    stdin_open: true

    # Restart policy
    restart: unless-stopped

    # Networks
    networks:
      - handover-rl-network

  # ============================================================================
  # TensorBoard - Experiment Tracking
  # ============================================================================
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: handover-rl-tensorboard

    volumes:
      - ./logs:/logs:ro

    ports:
      - "6007:6006"

    command: tensorboard --logdir=/logs --host=0.0.0.0 --port=6006

    restart: unless-stopped

    networks:
      - handover-rl-network

    depends_on:
      - handover-rl

  # ============================================================================
  # Jupyter Notebook - Interactive Development (Optional)
  # ============================================================================
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: handover-rl:v2.0
    container_name: handover-rl-jupyter

    volumes:
      - ./src:/app/src
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./notebooks:/app/notebooks
      - ../orbit-engine:/app/orbit-engine:ro

    environment:
      - PYTHONPATH=/app:/app/src:/app/orbit-engine
      - JUPYTER_ENABLE_LAB=yes

    ports:
      - "8889:8888"

    command: >
      bash -c "
      pip install jupyter jupyterlab ipykernel &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "

    restart: unless-stopped

    networks:
      - handover-rl-network

    # Only start if explicitly requested
    profiles:
      - jupyter

# ============================================================================
# Networks
# ============================================================================
networks:
  handover-rl-network:
    driver: bridge
    name: handover-rl-network

# ============================================================================
# Volumes (for data persistence)
# ============================================================================
volumes:
  data-volume:
    name: handover-rl-data
  checkpoints-volume:
    name: handover-rl-checkpoints
  logs-volume:
    name: handover-rl-logs
